version: '3.7'
services: 
    mysql-medinfo:
        image: mysql:latest
        restart: always
        container_name: mysql-medinfo-server
        ports: 
            - 3333:3306
        volumes:
            - mysql-medinfo:/var/lib/mysql
            - ./db-init/:/docker-entrypoint-initdb.d
        environment: 
            MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}

volumes: 
    mysql-medinfo:
        name: mysql-medinfo-data 